[Interface]
Address = 10.200.0.1/24
ListenPort = 51820
PrivateKey = gFL8OFA+TdAfzJ2RRtbyTNZj/AY4tVHlxWBRb4Bazms=

SaveConfig = false

[Peer]
PublicKey = cmzIZ6+kxV4Gxu0EXgfh1ouRJlAAIC9RLJ99rMbhNFc=
AllowedIPs = 10.200.0.2/32

# MikroTik Home
[Peer]
PublicKey = H82HaOV7JPJWJ07GNnkXuuAf2rWmsscvPrlYCZQ+Wm4=
AllowedIPs = 10.200.0.10/32,192.168.100.0/24,192.168.101.0/24
